services:
  db:
    image: postgres:latest
    container_name: forum_dsfr_db
    env_file:
      - credentials.env
    environment:
      POSTGRES_DB: forum_dsfr_db
    ports:
      - "5432:5432"
    volumes:
      - forum-db-data:/var/lib/postgresql/data
volumes:
  forum-db-data: