/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    ForumList: typeof import('./components/ForumList.vue')['default']
    MessageForm: typeof import('./components/MessageForm.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopicList: typeof import('./components/TopicList.vue')['default']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
