/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chargement: typeof import('./components/Chargement.vue')['default']
    ChargementSpinner: typeof import('./components/ChargementSpinner.vue')['default']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTable: typeof import('@gouvminint/vue-dsfr')['DsfrTable']
    ErreurMessage: typeof import('./components/ErreurMessage.vue')['default']
    ForumList: typeof import('./components/Forum/ForumList.vue')['default']
    Message: typeof import('./components/Message/Message.vue')['default']
    MessageForm: typeof import('./components/Message/MessageForm.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sujet: typeof import('./components/Sujet/Sujet.vue')['default']
    SujetBarreAction: typeof import('./components/Sujet/SujetBarreAction.vue')['default']
    SujetList: typeof import('./components/Sujet/SujetList.vue')['default']
    TopicList: typeof import('./components/TopicList.vue')['default']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
